# Generated by Django 5.0.6 on 2024-06-05 17:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Formulir',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('tempat_lahir', models.CharField(blank=True, max_length=255, null=True)),
                ('tanggal_lahir', models.DateField(default='')),
                ('nik', models.CharField(blank=True, max_length=16, null=True)),
                ('no_hp', models.CharField(blank=True, max_length=15, null=True)),
                ('no_hp_ortu', models.CharField(blank=True, max_length=15, null=True)),
                ('alamat', models.TextField(blank=True, max_length=255, null=True)),
                ('kelurahan', models.CharField(blank=True, max_length=255, null=True)),
                ('kecamatan', models.CharField(blank=True, max_length=255, null=True)),
                ('kabupaten', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('jenis_kelamin', models.CharField(blank=True, choices=[('Laki-Laki', 'Laki-Laki'), ('Perempuan', 'Perempuan')], max_length=10, null=True)),
                ('prodi1', models.CharField(blank=True, choices=[('S1 - Pendidikan Dokter', 'S1 - Pendidikan Dokter'), ('D4 - Analis Kesehatan', 'D4 - Analis Kesehatan'), ('S1 - Ilmu Kesehatan Masyarakat', 'S1 - Ilmu Kesehatan Masyarakat'), ('S1 - Gizi', 'S1 - Gizi'), ('S1 - PGSD', 'S1 - PGSD'), ('S1 - PGPAUD', 'S1 - PGPAUD'), ('S1 - Pendidikan Bahasa Inggris', 'S1 - Pendidikan Bahasa Inggris'), ('S1 - Akuntansi', 'S1 - Akuntansi'), ('S1 - Manajemen', 'S1 - Manajemen'), ('S1 - Sistem Informasi', 'S1 - Sistem Informasi'), ('S1 - Keperawatan', 'S1 - Keperawatan'), ('D3 - Keperawatan', 'D3 - Keperawatan'), ('D4 - Bidan', 'D4 - Bidan'), ('D3 - Kebidanan', 'D3 - Kebidanan')], max_length=50, null=True)),
                ('prodi2', models.CharField(blank=True, choices=[('S1 - Pendidikan Dokter', 'S1 - Pendidikan Dokter'), ('D4 - Analis Kesehatan', 'D4 - Analis Kesehatan'), ('S1 - Ilmu Kesehatan Masyarakat', 'S1 - Ilmu Kesehatan Masyarakat'), ('S1 - Gizi', 'S1 - Gizi'), ('S1 - PGSD', 'S1 - PGSD'), ('S1 - PGPAUD', 'S1 - PGPAUD'), ('S1 - Pendidikan Bahasa Inggris', 'S1 - Pendidikan Bahasa Inggris'), ('S1 - Akuntansi', 'S1 - Akuntansi'), ('S1 - Manajemen', 'S1 - Manajemen'), ('S1 - Sistem Informasi', 'S1 - Sistem Informasi'), ('S1 - Keperawatan', 'S1 - Keperawatan'), ('D3 - Keperawatan', 'D3 - Keperawatan'), ('D4 - Bidan', 'D4 - Bidan'), ('D3 - Kebidanan', 'D3 - Kebidanan')], default='', max_length=50, null=True)),
                ('prodi3', models.CharField(blank=True, choices=[('S1 - Pendidikan Dokter', 'S1 - Pendidikan Dokter'), ('D4 - Analis Kesehatan', 'D4 - Analis Kesehatan'), ('S1 - Ilmu Kesehatan Masyarakat', 'S1 - Ilmu Kesehatan Masyarakat'), ('S1 - Gizi', 'S1 - Gizi'), ('S1 - PGSD', 'S1 - PGSD'), ('S1 - PGPAUD', 'S1 - PGPAUD'), ('S1 - Pendidikan Bahasa Inggris', 'S1 - Pendidikan Bahasa Inggris'), ('S1 - Akuntansi', 'S1 - Akuntansi'), ('S1 - Manajemen', 'S1 - Manajemen'), ('S1 - Sistem Informasi', 'S1 - Sistem Informasi'), ('S1 - Keperawatan', 'S1 - Keperawatan'), ('D3 - Keperawatan', 'D3 - Keperawatan'), ('D4 - Bidan', 'D4 - Bidan'), ('D3 - Kebidanan', 'D3 - Kebidanan')], default='', max_length=50, null=True)),
                ('foto', models.ImageField(upload_to='uploads/')),
                ('status', models.CharField(choices=[('Belum Diverifikasi', 'Belum Diverifikasi'), ('Lulus', 'Lulus'), ('Gagal', 'Gagal')], default='Belum Diverifikasi', max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UploadFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(blank=True, max_length=50, null=True)),
                ('ijazah', models.FileField(upload_to='uploads/')),
                ('kk', models.FileField(upload_to='uploads/')),
                ('ktp', models.FileField(upload_to='uploads/')),
                ('raport10_1', models.FileField(upload_to='uploads/')),
                ('raport10_2', models.FileField(upload_to='uploads/')),
                ('raport11_1', models.FileField(upload_to='uploads/')),
                ('raport11_2', models.FileField(upload_to='uploads/')),
                ('raport12_1', models.FileField(upload_to='uploads/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
