# Generated by Django 5.0.6 on 2024-06-05 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pengguna', '0005_alter_uploadfile_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formulir',
            name='status',
            field=models.CharField(blank=True, choices=[('Belum Diverifikasi', 'Belum Diverifikasi'), ('Lulus', 'Lulus'), ('Gagal', 'Gagal')], default='Belum Diverifikasi', max_length=20, null=True),
        ),
    ]
